name: caddemiz
favicon: null
layout_spectrum: 0.67236
typography_spectrum: 0.5641233623027802
title: 'your imagined and imaginative boulevard of ideas, character, and story'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d3510'
    - '#000000'
    - '#ffffff'
    - '#868580'
    - '#bc2709'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
