name: caddemiz
favicon: null
layout_spectrum: 0.43587
typography_spectrum: 0.07862
title: 'an imagined and imaginative boulevard of character, color, ideas, and story'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e3a24'
    - '#d2d0c5'
    - '#f9f3e4'
    - '#acaa97'
    - '#817d64'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
