name: caddemiz
favicon: null
layout_spectrum: 0.26259441394358873
typography_spectrum: 0.5641233623027802
title: an imagined and imaginative boulevard of story
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.10952803259715438
  lightness: 0.9376167969312519
  saturation: 0.08094278443604708
  rhythmicContrast: 0.4730466129258275
purpose: []
