name: caddemiz
favicon: null
layout_spectrum: 0.43587
typography_spectrum: 0.07862
title: 'an imagined and imaginative boulevard of character, color, ideas, and story'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d3510'
    - '#000000'
    - '#ffffff'
    - '#868580'
    - '#bc2709'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
