name: caddemiz
favicon: null
layout_spectrum: 0.01303
typography_spectrum: 0.07862
title: 'an imagined and imaginative boulevard of character, color, ideas, and story'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff2400'
    - '#dbd7cb'
    - '#67675f'
    - '#aaa78c'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
